ssl_path: "./ssl/"
cert_file_name: "cert.pem"
key_file_name: "key.pem"

aliyun:
  enabled: true
  enabled_products:
    - cdn
    - live
  access_key: "AccessKey ID"
  access_token: "AccessKey Secret"

tencent:
  enabled: true
  enabled_products:
    - cdn
    - apigateway
  secret_id: "TENCENT_SECRET_ID"
  secret_key: "TENCENT_SECRET_KEY"
  regions:
    - ap-singapore
    - ap-tokyo

dogecloud:
  enabled: true
  enabled_products:
    - cdn
  access_key: "DOGECLOUD_ACCESS_KEY"
  access_token: "DOGECLOUD_ACCESS_TOKEN"
